#!/usr/bin/env bash
# installs nginx and configures it on a remote server
apt-get upgrade
apt-get -y install nginx
sudo ufw allow 'Nginx HTTP'
chmod 755 -R /var/www/html
echo 'Hello World!' > /var/www/html/index.nginx-debian.html
service nginx start
