#!/usr/bin/env bash
# prints goodluck and school
val=1
while [ $val -le 10 ]
do
	if [ $val -eq 4 ]
	then
		echo "bad luck"
	elif [ $val -eq 8 ]
	then 
		echo "good luck"
	else
		echo "Best School"
	fi
	val=$(( val+1 ))
done
